apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-image
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-image
spec:
  selector:
    matchLabels:
      app: flask-image
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-image
    spec:
      containers:
      - name: flask-image
        image: myjccontainerregistry.azurecr.io/flask-image:latest
        ports:
        - containerPort: 5000