name: TF Deploy in Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Login Azure CLI
      shell: pwsh
      run: |
        az login --service-principal -u "${{secrets.SERVICEPRINCIPALID}}" -p "${{secrets.SECRET}}" --tenant "${{secrets.TENANTID}}"
    - name: Install Terraform CLI
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        wget -O- https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          sudo tee ./hashicorp-archive-keyring.gpg
        gpg --no-default-keyring \
          --keyring ./hashicorp-archive-keyring.gpg \
          --fingerprint
        sudo ./hashicorp-archive-keyring.gpg
        sudo apt update
        sudo apt-get install terraform
