name: TF Deploy in Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Login Azure CLI
      shell: pwsh
      run: |
        az login --service-principal -u "${{secrets.SERVICEPRINCIPALID}}" -p "${{secrets.SECRET}}" --tenant "${{secrets.TENANTID}}"
    - name: Install Terraform CLI
      run: |
        sudo apt-get install unzip
        wget https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_windows_amd64.zip
        unzip terraform_1.3.3_windows_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version


